version: '3.9'
services:
  development:
    container_name: app-02-rincourse
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - /workspaces/app-02-rincourse/node_modules
